const fs = require('fs');
let code = fs.readFileSync('server.ts', 'utf8');
const target = `      const smtpPort = String(process.env.SMTP_PORT || "587").trim();
      const isSecure = smtpPort === "465" || String(process.env.SMTP_SECURE).trim() === "true";
      const smtpHost = String(process.env.SMTP_HOST).trim();
      const smtpUser = String(process.env.SMTP_USER).trim();
      const smtpPass = String(process.env.SMTP_PASS).trim();`;
const replacement = `      const smtpPort = (process.env.SMTP_PORT || "587").trim();
      const isSecure = smtpPort === "465" || (process.env.SMTP_SECURE || "").trim() === "true";
      const smtpHost = (process.env.SMTP_HOST || "").trim();
      const smtpUser = (process.env.SMTP_USER || "").trim();
      const smtpPass = (process.env.SMTP_PASS || "").trim();`;
code = code.replace(target, replacement);
fs.writeFileSync('server.ts', code);
