const fs = require('fs');
const file = 'src/components/Procurement/ProcurementView.tsx';
let content = fs.readFileSync(file, 'utf8');

const t1 = 'className="bg-white border-2 border-gray-50 rounded-[2rem] p-5 flex items-center justify-between group hover:border-blue-100 transition-all"\n                                                       >\n                                                           <div className="flex items-center gap-4">';
const r1 = 'className="bg-white border-2 border-gray-50 rounded-[2rem] p-5 flex flex-col gap-4 group hover:border-blue-100 transition-all"\n                                                       >\n                                                           <div className="flex items-start justify-between min-w-0">\n                                                               <div className="flex items-center gap-4 min-w-0">';
content = content.replaceAll(t1, r1);

const t2 = '<div className={cn("w-12 h-12 rounded-2xl flex items-center justify-center", config.bg)}>\n                                                                   <config.icon className={cn("w-6 h-6", config.color)} />\n                                                               </div>\n                                                               <div className="text-left">\n                                                                   <div className="flex items-center gap-2 mb-1">\n                                                                       <span className="text-[11px] font-black text-gray-900">{item.invoiceNumber || "Без номера"}</span>';
const r2 = '<div className={cn("w-12 h-12 rounded-2xl flex items-center justify-center shrink-0", config.bg)}>\n                                                                   <config.icon className={cn("w-6 h-6", config.color)} />\n                                                               </div>\n                                                               <div className="text-left min-w-0 w-full">\n                                                                   <div className="flex items-center gap-2 mb-1">\n                                                                       <span className="text-[11px] font-black text-gray-900 truncate">{item.invoiceNumber || "Без номера"}</span>';
content = content.replaceAll(t2, r2);

const t3 = '<span className={cn("text-[8px] font-black px-2 py-0.5 rounded-full border", config.bg, config.color, config.border)}>\n                                                                           {item.status}\n                                                                       </span>\n                                                                   </div>\n                                                                   <div className="flex items-center gap-3">\n                                                                       <span className="text-[10px] font-bold text-gray-400 flex items-center gap-1">\n                                                                           <Truck className="w-3 h-3" />\n                                                                           {supplier?.name || "Поставщик не указан"}\n                                                                       </span>\n                                                                       {item.arrivalDate && (\n                                                                           <span className="text-[10px] font-bold text-blue-400 flex items-center gap-1">\n                                                                               <Calendar className="w-3 h-3" />';
const r3 = '<span className={cn("text-[8px] font-black px-2 py-0.5 rounded-full border shrink-0", config.bg, config.color, config.border)}>\n                                                                           {item.status}\n                                                                       </span>\n                                                                   </div>\n                                                                   <div className="flex flex-wrap items-center gap-y-1 gap-x-3">\n                                                                       <span className="text-[10px] font-bold text-gray-400 flex items-center gap-1 min-w-0">\n                                                                           <Truck className="w-3 h-3 shrink-0" />\n                                                                           <span className="truncate">{supplier?.name || "Поставщик не указан"}</span>\n                                                                       </span>\n                                                                       {item.arrivalDate && (\n                                                                           <span className="text-[10px] font-bold text-blue-400 flex items-center gap-1 shrink-0">\n                                                                               <Calendar className="w-3 h-3" />';
content = content.replaceAll(t3, r3);

const t4 = '</div>\n                                                           </div>\n                                                           <div className="flex items-center gap-3">\n                                                               <div className="text-right mr-4">';
const r4 = '</div>\n                                                               </div>\n                                                           <div className="flex items-center gap-3 shrink-0">\n                                                               <div className="text-right hidden sm:block mr-2">';
content = content.replaceAll(t4, r4);

const t5 = '</button>\n                                                           </div>\n                                                       </div>\n                                                   );';
const r5 = '</button>\n                                                           </div>\n                                                           </div>\n                                                            {item.comment && (\n                                                                <div className="bg-rose-50 border border-rose-100 rounded-xl p-3 flex items-start gap-2.5 ml-0 sm:ml-16">\n                                                                    <MessageSquare className="w-4 h-4 text-rose-500 shrink-0 mt-0.5" />\n                                                                    <div className="flex flex-col gap-0.5">\n                                                                        <span className="text-[10px] font-black uppercase tracking-widest text-rose-600">Комментарий склада</span>\n                                                                        <span className="text-xs text-rose-700">{item.comment}</span>\n                                                                    </div>\n                                                                </div>\n                                                            )}\n                                                       </div>\n                                                   );';
content = content.replaceAll(t5, r5);

fs.writeFileSync(file, content);
